server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;

    location = / {
        default_type text/plain;
        try_files /install.sh =404;
    }

    location /install.sh {
        default_type text/plain;
    }

    location /install.ps1 {
        default_type text/plain;
    }

    location /index.html {
        try_files $uri =404;
    }
}
