server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;

    location / {
        index index.html;
        try_files $uri $uri/ =404;
    }

    location /install.sh {
        default_type text/plain;
    }

    location /install.ps1 {
        default_type text/plain;
    }
}
